### ISSUE TITLE
update_object blocks

### ISSUE THREAD

**Issue by ctaque** [nicompte/algoliasearch-rs#2]
Hi, nice work, it's what I'm looking for.

I'm having trouble to make a update object work. I can call the function index.update_object(obj)
but it blocks there. Need to mention that I use executor::block_on to wait for the future to resolve  

```rust
   use futures::executor;
   executor::block_on(index.update_object(obj))
  // never reaches here
```

here is the function : 

```rust
    fn update_algolia(obj: T, index_name: String) -> Result<UpdateOperationResult, AlgoliaError>
    where Self: std::marker::Sized ,
          T: serde::de::DeserializeOwned + serde::Serialize + std::fmt::Debug {
        let index: Index<T> = Self::get_index(index_name);
        executor::block_on(index.update_object(obj))
    }
```

I checked my settings, index name.. the only thing I don't do is to transform the object to save to match the already saved objects in the index (the structure is different)

It would be great to have your opinion on this.
Thanks

**Comment by nicompte** [comment]
Hey,

Did you get it to work?
I'm not familiar with `executor::block_on`, let me try that.

**Comment by ctaque** [comment]
Hi,
I couldn’t make it work, I saw an error on the request paths which have an extra /1 for the api version in some requests. Even by correcting this I couldn’t make it work.
The request seems to be sent by I never get a response.

**Comment by nicompte** [comment]
You were right about the extra `/1`. I've published a new version that should fix that. It also changes the api, since `update_object` now requires the `object_id`.

I've also add a `get_task_status` method.

Could you try it and tell me if it fixes your issue?

**Comment by ctaque** [comment]
I’ll check it when I have time.
