### ISSUE TITLE
Camel case query params

### ISSUE THREAD

**Issue by elilabes** [nicompte/algoliasearch-rs#20]
Hi there,

I have not been able to use the query builder working.

```rust
SearchQueryBuilder::default()
            .page(1)
            .hits_per_page(6)
```

This outputs as the body params as `page=0&hits_per_page=6`, which doesn't appear to be valid for Algolia. It needs to be `page=0&hitsPerPage=6`. Am I doing something wrong or is this an issue? Maybe bought on by an API change from Algolia.

**Comment by nicompte** [comment]
Hello, thanks for reporting this, there was actually an issue during serialization. Could you check if the new version fixes your issue? See https://github.com/nicompte/algoliasearch-rs/commit/c06de12a99cb1be6cbddaeb5edafb120e2a4b933.

**Comment by elilabes** [comment]
Thanks @nicompte - that fixed it!

**Comment by nicompte** [comment]
Alright, thanks again for reporting!
